const state = {mode:'live',data:null,query:'',filter:'all',horizon:30,dataCache:new Map(),researchRuns:new Map(),fixtures:null,zipIndex:null,quickRegistry:null,sourceConnectors:null,smokeTests:null,entityCache:new Map(),americusProfile:null};
const researchNeeded='RESEARCH NEEDED';
const statusClass=(status)=>`status-${String(status||'').toLowerCase().replace(/\s+/g,'-').replace(/[^a-z-]/g,'')}`;
const els={
  modeButtons:[...document.querySelectorAll('.mode-button')],search:document.querySelector('#community-search'),input:document.querySelector('#search-input'),help:document.querySelector('#search-help'),americus:document.querySelector('#americus-button'),featuredAmericus:document.querySelector('#featured-americus-button'),pinehaven:document.querySelector('#pinehaven-button'),reset:document.querySelector('#reset-button'),liveNotice:document.querySelector('#live-notice'),liveNoticeTitle:document.querySelector('#live-notice-title'),liveNoticeCopy:document.querySelector('#live-notice-copy'),liveNoticeBadge:document.querySelector('#live-notice-badge'),quickView:document.querySelector('#quick-view'),quickTitle:document.querySelector('#quick-view-title'),quickState:document.querySelector('#quick-view-state'),quickSummary:document.querySelector('#quick-view-summary'),quickDisclosure:document.querySelector('#quick-demo-disclosure'),progress:document.querySelector('#research-progress'),quickIdentity:document.querySelector('#quick-identity'),quickFunding:document.querySelector('#quick-funding'),quickOperations:document.querySelector('#quick-operations'),quickFinancials:document.querySelector('#quick-financials'),quickUtilities:document.querySelector('#quick-utilities'),quickConditions:document.querySelector('#quick-conditions'),quickSignals:document.querySelector('#quick-signals'),quickSchools:document.querySelector('#quick-schools'),quickInfrastructure:document.querySelector('#quick-infrastructure'),quickAssets:document.querySelector('#quick-assets'),quickOpportunities:document.querySelector('#quick-opportunities'),quickSources:document.querySelector('#quick-sources'),americusProfile:document.querySelector('#americus-deep-profile'),americusNav:document.querySelector('#americus-section-nav'),americusStack:document.querySelector('#americus-section-stack'),badge:document.querySelector('#profile-badge'),scoreGrid:document.querySelector('#score-grid'),researchGrid:document.querySelector('#research-grid'),nav:document.querySelector('#section-nav'),pathway:document.querySelector('#pathway-flow'),opportunities:document.querySelector('#opportunity-grid'),sources:document.querySelector('#source-list'),dialog:document.querySelector('#score-dialog'),dialogTitle:document.querySelector('#score-dialog-title'),dialogBody:document.querySelector('#score-dialog-body'),close:document.querySelector('#dialog-close'),toast:document.querySelector('#toast'),geographyChain:document.querySelector('#geography-chain'),relationshipTags:document.querySelector('#relationship-tags'),narrative:document.querySelector('#narrative-stack'),fiscal:document.querySelector('#fiscal-layer'),enterprise:document.querySelector('#enterprise-layer'),capitalMatches:document.querySelector('#capital-match-layer'),futureResearch:document.querySelector('#future-research-layer'),legacy:document.querySelector('#legacy-grid'),researchControl:document.querySelector('#research-control')
};

async function loadJsonCached(path){if(state.dataCache.has(path))return state.dataCache.get(path);state.researchRuns.set(path,(state.researchRuns.get(path)||0)+1);const response=await fetch(path);if(!response.ok)throw new Error(`Unable to load ${path}`);const data=await response.json();state.dataCache.set(path,data);return data;}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function setText(id,value){document.querySelector(`#${id}`).textContent=value||researchNeeded;}
function badge(status){return `<span class="badge ${statusClass(status)}">${escapeHtml(status)}</span>`;}
async function resolveFixture(query){if(!state.fixtures)state.fixtures=await loadJsonCached('data/geography-resolver-fixtures.json');const normalized=query.trim().toLowerCase().replace(/,\s*/g,' ');return state.fixtures.fixtures.find((fixture)=>fixture.match.includes(normalized))||null;}

const pinehavenOnlySelectors=['#profile','#geography-resolver','#community-intelligence','.system-layers','#scorecard','.research-dashboard','#pathway','#hub','#opportunities','#legacy','#sources'];
function setViewMode(isLive){els.quickView.hidden=!isLive;if(!isLive)els.americusProfile.hidden=true;pinehavenOnlySelectors.forEach((selector)=>{const node=document.querySelector(selector);if(node)node.hidden=isLive;});}
function normalizeQuery(value){return String(value||'').trim().toLowerCase().replace(/,\s*/g,' ').replace(/\s+/g,' ');}
function sourceSearchUrl(base,query){return `${base}${base.includes('?')?'&':'?'}search=${encodeURIComponent(query)}`;}
function setPublicRoute(query,isAmericus=false){document.documentElement.classList.toggle('case-route',isAmericus);const url=new URL(window.location.href);if(query)url.searchParams.set('location',query);else url.searchParams.delete('location');window.history.replaceState({},'',url);}

async function loadQuickViewResources(){
  const [zipIndex,quickRegistry,sourceConnectors,smokeTests]=await Promise.all([
    loadJsonCached('data/georgia-zip-index.json'),
    loadJsonCached('data/quick-view-registry.json?v=20260913.5'),
    loadJsonCached('data/source-connectors.json?v=20260913.5'),
    loadJsonCached('data/generic-zip-smoke-tests.json?v=20260913.1')
  ]);
  state.zipIndex=zipIndex;state.quickRegistry=quickRegistry;state.sourceConnectors=sourceConnectors;state.smokeTests=smokeTests;
}

function smokeGeorgiaQuickView(query,rows,smoke){
  const data=genericGeorgiaQuickView(query,rows);const institutionSources=smoke.sources.map((url,index)=>({id:`smoke-${smoke.zip}-${index+1}`,title:smoke.source_types[index]||'Official public source',publisher:new URL(url).hostname.replace(/^www\./,''),type:'Official source lane',date:'Current public path',retrieval_date:'2026-09-13',url}));
  data.status='PRELIMINARY';data.research_status='CACHED';data.smoke_test_only=true;data.sources=institutionSources;data.unknowns=smoke.limitations;
  data.financial_baseline=smoke.populated_categories.includes('municipal finance')||smoke.populated_categories.includes('school finance')?[{entity:data.community.municipality,latest_audited_period:'Latest source linked in bounded smoke test',current_public_signal:'Financial source lane populated; no audit analysis performed',status:'VERIFIED'}]:[];
  data.fiscal_measures=smoke.populated_categories.includes('public capital')?[{type:'Public capital',role:'Official source index located',detail:'A public-capital source lane is available; measure-level validation was outside this smoke test.',categories:['Public investment'],status:'VERIFIED',source_type:'Official'}]:[];
  data.operating_revenue=[];
  data.enterprise_funds=smoke.populated_categories.some((item)=>/utilit|water|energy/.test(item))?[{name:'Public utility context located',accounting_boundary:'Provider and service remain address-specific',detail:'The bounded test located a public utility source. It does not establish project-specific capacity.',status:'VERIFIED'}]:[];
  data.schools_youth=[{title:smoke.school_district,detail:'Official school-system lane resolved; address assignment and detailed outcomes require the appropriate school source.',status:'VERIFIED'}];
  data.assets=smoke.populated_categories.filter((item)=>/education|economic development|workforce/.test(item)).map((item)=>({title:item.replace(/\b\w/g,(char)=>char.toUpperCase()),detail:'An official institutional source was located in the bounded retrieval check.',status:'VERIFIED'}));
  data.recent_signals=[];
  data.community_conditions=smoke.populated_categories.slice(0,5).map((category,index)=>({condition_id:`${smoke.zip}-${index+1}`,category,title:category.replace(/\b\w/g,(char)=>char.toUpperCase()),description:'A useful official source lane is available for deeper current-record extraction.',status:'VERIFIED',source_ids:[institutionSources[Math.min(index,institutionSources.length-1)].id]}));
  data.opportunities=[{title:'Retrieval architecture verified',condition:`${smoke.source_count} bounded public-source lanes connected for ${smoke.resolved_jurisdiction}.`,connection:'A normal research run would extract current conditions and funding before generating any opportunity recommendation.',status:'INFERENCE'}];
  data.entity_cache=institutionSources.map((source)=>({key:`${data.community.county.toLowerCase().replace(/\W+/g,'_')}:public_source:current:${source.id}`,source_id:source.id}));
  return data;
}

function genericGeorgiaQuickView(query,rows){
  const primary=rows[0];const place=primary.place;const county=primary.county;
  const related=state.zipIndex.zips.filter((row)=>row.place===place&&row.county===county).map((row)=>row.zip);
  const ballotQuery=`${county} ${place} Georgia SPLOST E-SPLOST T-SPLOST bond referendum`;
  const officialPaths=[
    {id:'dca-path',title:`DCA local-government search path for ${county}`,publisher:'Georgia Department of Community Affairs',type:'State Data',date:'current search path',retrieval_date:'On demand',url:'https://dca.georgia.gov/community-assistance/government-authority-reporting/research-and-surveys/research-and-surveys'},
    {id:'doaa-path',title:`DOAA audit search path for ${county} and ${place}`,publisher:'Georgia Department of Audits & Accounts',type:'Audit',date:'current search path',retrieval_date:'On demand',url:'https://www.audits2.ga.gov/'},
    {id:'gadoe-path',title:`GaDOE school-system data path for ${county}`,publisher:'Georgia Department of Education',type:'State Data',date:'current search path',retrieval_date:'On demand',url:'https://georgiainsights.gadoe.org/'},
    {id:'ballotpedia-path',title:'Ballotpedia referendum discovery path',publisher:'Ballotpedia',type:'Ballot Measure / Discovery',date:'on-demand query',retrieval_date:'On demand',url:`https://ballotpedia.org/wiki/index.php?search=${encodeURIComponent(ballotQuery)}`}
  ];
  return {
    mode:'live-public-data-preview',status:'INSUFFICIENT_EVIDENCE',research_status:'NEW_RESEARCH_REQUIRED',retrieval_date:new Date().toISOString().slice(0,10),
    community:{name:`${place} / ${county}, Georgia`,municipality:place,county,population:'Research Needed',utility:'Service territories require official validation',rail:'Research Needed',signal:'Public-source lanes prepared; no capacity claim',confidence:'Geography resolved; evidence retrieval incomplete',classification:'Preliminary — deeper research required'},
    geography_resolution:{search_geography:query,municipalities:[place],county,zip_codes:related.length?related:[primary.zip],utility_service_areas:['Address-level electric, water, sewer, gas and broadband validation required'],school_districts:[`${county} public-school assignment requires official validation`],development_authorities:[`${county} and municipal authority relationships require validation`],rail_corridors:['Research Needed'],tags:['Georgia Postal Discovery','County Relationship','Service Areas Require Verification']},
    entities:[{entity_id:county.toLowerCase().replace(/\W+/g,'_'),name:`${county} Government`,role:'County government target',status:'NEW_RESEARCH_REQUIRED'},{entity_id:place.toLowerCase().replace(/\W+/g,'_'),name:place,role:'Municipal government target where incorporated',status:'NEW_RESEARCH_REQUIRED'}],
    financial_baseline:[{entity:county,latest_audited_period:'RESEARCH NEEDED',current_public_signal:'Official audit, DCA finance and budget paths prepared',status:'RESEARCH NEEDED'},{entity:place,latest_audited_period:'RESEARCH NEEDED',current_public_signal:'Municipal incorporation and financial-source validation required',status:'RESEARCH NEEDED'},{entity:`${county} school system`,latest_audited_period:'RESEARCH NEEDED',current_public_signal:'GaDOE and DOAA discovery paths prepared',status:'RESEARCH NEEDED'}],
    fiscal_measures:[['SPLOST','Capital projects'],['E-SPLOST','School capital'],['T-SPLOST / TIA','Transportation capital'],['LOST','Operating revenue'],['Bonds','Debt-financed capital']].map(([type,role])=>({type,role,detail:'Discovery path prepared; official measure validation not yet complete.',categories:['RESEARCH NEEDED'],status:'RESEARCH NEEDED',source_type:type==='LOST'?'Audit':'Ballot Measure'})),
    operating_revenue:[{name:'LOST and property taxes',detail:'Current revenue mix requires the latest audit and DCA reporting.',status:'RESEARCH NEEDED'},{name:'Enterprise utilities',detail:'Any proprietary activity must remain separate from ordinary General Fund revenue.',status:'RESEARCH NEEDED'}],
    enterprise_funds:[{name:'Water, sewer, gas, electric, sanitation or broadband enterprises',accounting_boundary:'Proprietary activity — not ordinary General Fund revenue',detail:'Provider, finances, rates, debt, reserves, transfers and capital plans require entity-level research.',status:'RESEARCH NEEDED'}],
    infrastructure_projects:[],recent_signals:[{category:'Government',date:'On demand',title:'Official current-signal search prepared',summary:'The quick view resolved Georgia geography; current official and local-publication retrieval remains incomplete.',status:'RESEARCH NEEDED',source_type:'Official'}],
    schools_youth:[{title:'Public school system',detail:'District assignment, enrollment, graduation, CTAE and E-SPLOST require official validation.',status:'RESEARCH NEEDED'},{title:'Youth and community life',detail:'Sports, arts, recreation, teen and technology-creation programs require a local inventory.',status:'RESEARCH NEEDED'}],
    assets:[{title:`${place} and ${county}`,detail:'Community assets, institutions, downtown, parks, health care, colleges and civic facilities require public-source review.',status:'RESEARCH NEEDED'}],
    opportunities:[{title:'Evidence-first opportunity scan',condition:'Georgia geography is resolved, but community priorities and constraints are not yet documented.',connection:'Complete official financial, ballot, utility, school, asset and community-signal lanes before drawing conclusions.',status:'INFERENCE'}],
    referendum_discovery:{ballotpedia_query:ballotQuery,ballotpedia_url:officialPaths[3].url,status:'DISCOVERY_PATH_READY',validation_rule:'Ballotpedia is discovery/context only. Official ballot language, resolutions, election records or audited schedules are required.',official_validation_status:'NOT_RUN'},
    entity_cache:[],sources:officialPaths,unknowns:['Latest audits and budgets','Validated ballot measures and project lists','Utility service territories and engineering capacity','School-system assignment and outcomes','Current community signals and asset inventory'],human_review_required:true
  };
}

async function resolveGeorgiaQuickView(query){
  await loadQuickViewResources();const normalized=normalizeQuery(query);const numeric=/^\d{5}$/.test(normalized);
  const profile=state.quickRegistry.profiles.find((item)=>item.match.includes(normalized));
  if(profile){const result=structuredClone(profile);result.geography_resolution.search_geography=query;return {data:result};}
  let rows=[];
  if(numeric)rows=state.zipIndex.zips.filter((row)=>row.zip===normalized);
  else rows=state.zipIndex.zips.filter((row)=>normalizeQuery(row.place)===normalized||normalizeQuery(row.county)===normalized||normalizeQuery(`${row.county} georgia`)===normalized);
  if(!rows.length)return {error:numeric?'Community Forward Georgia currently analyzes Georgia communities only.':'No Georgia ZIP, city, or county match was found. Try a five-digit Georgia ZIP code.'};
  const smoke=numeric?state.smokeTests.tests.find((item)=>item.zip===normalized):null;
  if(smoke)return {data:smokeGeorgiaQuickView(query,rows,smoke)};
  return {data:genericGeorgiaQuickView(query,rows)};
}

function renderQuickItems(target,items,template){target.innerHTML=(items?.length?items:[{title:researchNeeded,detail:'Public-source research is required.',status:researchNeeded}]).map(template).join('');}
function renderQuickView(data){
  const g=data.geography_resolution||{};const preloaded=Boolean(data.smoke_test_only);els.quickTitle.textContent=preloaded?'Demo Quick View':'Researching… Demo';els.quickState.textContent=preloaded?'Preloaded demonstration evidence':'Workflow preview';els.liveNoticeTitle.textContent=preloaded?'Demo Quick View':'Researching… Demo';els.liveNoticeCopy.textContent=preloaded?'Preloaded demonstration evidence':'Community Forward is resolving the community and showing the research lanes that would be used in a live analysis.';els.liveNoticeBadge.textContent='Demo';els.quickSummary.textContent=preloaded?`${data.community.name}. Preloaded demonstration evidence is organized by public entity; ZIP is an entry point, not the service-area boundary.`:'Community Forward is resolving the community and showing the research lanes that would be used in a live analysis.';els.quickDisclosure.innerHTML='<strong>Public demo:</strong> Live research services are not connected yet. This preview shows the governed research workflow and any evidence already included in the demonstration dataset.';
  const progress=preloaded?[['Resolving community','Resolved'],['Financial evidence','Preloaded'],['Ballot measures','Needs research'],['Utility evidence','Preloaded'],['School evidence','Preloaded'],['Current community signals','Needs research']]:[['Resolving community','Resolved'],['Financial evidence','Not connected'],['Ballot measures','Not connected'],['Utility evidence','Not connected'],['School evidence','Not connected'],['Current community signals','Not connected']];
  els.progress.innerHTML=progress.map(([label,status])=>`<div><span aria-hidden="true">${/Resolved|Preloaded/.test(status)?'✓':'…'}</span><strong>${escapeHtml(label)}</strong><small>${escapeHtml(status)}</small></div>`).join('');
  const identity=[['ZIP / input',state.query],['City',(g.municipalities||[]).join(', ')],['County',g.county],['Related ZIPs',(g.zip_codes||[]).join(', ')],['School district',(g.school_districts||[]).join(', ')],['Utility / service areas',(g.utility_service_areas||[]).join(' · ')]];
  els.quickIdentity.innerHTML=identity.map(([label,value])=>`<article><span>${escapeHtml(label)}</span><strong>${escapeHtml(value||researchNeeded)}</strong></article>`).join('');
  renderQuickItems(els.quickFunding,data.fiscal_measures,(item)=>`<div class="quick-item"><div><strong>${escapeHtml(item.type)}</strong><small>${escapeHtml(item.role)}</small></div>${badge(item.status)}<p>${escapeHtml(item.detail)}</p><div class="category-tags">${(item.categories||[]).map((category)=>`<span>${escapeHtml(category)}</span>`).join('')}</div></div>`);
  renderQuickItems(els.quickOperations,data.operating_revenue,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.name||item.title)}</strong>${badge(item.status)}<p>${escapeHtml(item.detail)}</p></div>`);
  renderQuickItems(els.quickFinancials,data.financial_baseline,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.entity)}</strong>${badge(item.status)}<dl><dt>Latest Audited Period</dt><dd>${escapeHtml(item.latest_audited_period)}</dd><dt>Current Public Signals</dt><dd>${escapeHtml(item.current_public_signal)}</dd></dl></div>`);
  renderQuickItems(els.quickUtilities,data.enterprise_funds,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.name)}</strong>${badge(item.status)}<small>${escapeHtml(item.accounting_boundary)}</small><p>${escapeHtml(item.detail||item.ratepayer_benefit)}</p></div>`);
  const conditions=data.community_conditions?.length?data.community_conditions:(data.recent_signals||[]).slice(0,6).map((item,index)=>({condition_id:`signal-${index}`,category:item.category,title:item.title,description:item.summary,status:item.status,source_ids:[]}));
  renderQuickItems(els.quickConditions,conditions,(item)=>`<div class="signal-item"><span class="signal-category">${escapeHtml(item.category)}</span><div><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.description||item.short_description)}</p>${item.source_ids?.length?`<small>Sources: ${item.source_ids.map(escapeHtml).join(' · ')}</small>`:''}</div>${badge(item.status||item.evidence_status)}</div>`);
  renderQuickItems(els.quickSignals,data.recent_signals,(item)=>`<div class="signal-item"><span class="signal-category">${escapeHtml(item.category)}</span><div><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.date)} · ${escapeHtml(item.source_type)}</small><p>${escapeHtml(item.summary)}</p></div>${badge(item.status)}</div>`);
  renderQuickItems(els.quickSchools,data.schools_youth,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.title)}</strong>${badge(item.status)}<p>${escapeHtml(item.detail)}</p></div>`);
  const infrastructure=[...(data.infrastructure_projects||[]).map((item)=>({title:item.name,detail:`Location ${item.project_location_zip}; ${item.potential_service_area_impact}. Confirmed capacity: ${item.confirmed_capacity_impact??'Unknown — no capacity claim'}. Utility verification required: ${item.requires_utility_verification?'Yes':'No'}.`,status:item.evidence_status})),{title:'Electric, rail, broadband and highway systems',detail:'Service-area and corridor relevance may cross ZIPs. Proximity does not establish capacity, easements or project fit.',status:'RESEARCH NEEDED'}];
  renderQuickItems(els.quickInfrastructure,infrastructure,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.title)}</strong>${badge(item.status)}<p>${escapeHtml(item.detail)}</p></div>`);
  renderQuickItems(els.quickAssets,data.assets,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.title)}</strong>${badge(item.status)}<p>${escapeHtml(item.detail)}</p></div>`);
  renderQuickItems(els.quickOpportunities,data.opportunities,(item)=>`<div class="quick-item"><strong>${escapeHtml(item.title)}</strong>${badge(item.status)}<p><b>Starts with:</b> ${escapeHtml(item.condition)}</p><p><b>Study next:</b> ${escapeHtml(item.connection)}</p></div>`);
  const ballot=data.referendum_discovery||{};const sources=data.sources||[];
  els.quickSources.innerHTML=`<div class="source-path-note"><strong>Ballotpedia referendum discovery</strong><p>${escapeHtml(ballot.validation_rule||'Discovery only; official validation required.')}</p>${ballot.ballotpedia_url?`<a href="${escapeHtml(ballot.ballotpedia_url)}" target="_blank" rel="noopener">Open Ballotpedia discovery search ↗</a>`:''}</div><div class="quick-source-grid">${sources.map((source)=>`<a href="${escapeHtml(source.url)}" target="_blank" rel="noopener"><span>${escapeHtml(source.type)}</span><strong>${escapeHtml(source.title)}</strong><small>${escapeHtml(source.publisher)} · ${escapeHtml(source.date)} · retrieved ${escapeHtml(source.retrieval_date)}</small></a>`).join('')}</div><div class="unknown-list"><strong>Still requires confirmation</strong><ul>${(data.unknowns||[]).map((item)=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></div>`;
  (data.entity_cache||[]).forEach((item)=>state.entityCache.set(item.key,item));
  const useful=(items)=>items?.some((item)=>!/(research needed|new_research_required)/i.test(item.status||item.evidence_status||''));
  [[els.quickFunding,data.fiscal_measures],[els.quickOperations,data.operating_revenue],[els.quickFinancials,data.financial_baseline],[els.quickUtilities,data.enterprise_funds],[els.quickConditions,conditions],[els.quickSignals,data.recent_signals],[els.quickSchools,data.schools_youth],[els.quickAssets,data.assets],[els.quickOpportunities,data.opportunities]].forEach(([target,items])=>{if(target?.closest('.quick-panel'))target.closest('.quick-panel').hidden=!useful(items);});
}

function renderAmericusProfile(data){
  state.americusProfile=data;
  const sourceMap=new Map((data.sources||[]).map((source)=>[source.id,source]));
  const sectionMap=new Map((data.sections||[]).map((section)=>[section.title,section]));
  const sourceLinks=(ids)=>`<div class="case-source-links">${ids.map((id)=>{const source=sourceMap.get(id);return source?`<a href="${escapeHtml(source.url)}" target="_blank" rel="noopener">${escapeHtml(source.title)} ↗</a>`:'';}).join('')}</div>`;
  const evidenceControl=(label,ids,body='')=>`<details class="evidence-drawer"><summary>${escapeHtml(label)}</summary>${body}${sourceLinks(ids)}</details>`;
  const caseCard=(title,detail,status='INFERENCE')=>`<article class="case-card">${badge(status)}<h3>${escapeHtml(title)}</h3><p>${escapeHtml(detail)}</p></article>`;
  const priorities=[
    ['Schools + Recreation','VERIFIED E-SPLOST investment','One cent for up to 20 quarters; $45M collection cap; separate $50M GO bond authorization; sports complex and technology included; approved 3,263–1,022 (76.15%), all 11 precincts reporting.'],
    ['Workforce + Education','Connected institutions','SGTC, GSW, Ignite College & Career Academy, and existing technical pathways'],
    ['Economic Development','Sites, industry, and downtown','Southerfield readiness, NanoPV activity, industrial development, and downtown improvements'],
    ['Community Infrastructure','Public systems','Drinking-water capital, municipal utilities, and transportation investment'],
    ['Social Infrastructure','People and participation','Childcare, housing partnerships, and youth leadership'],
    ['Rail + Regional Connectivity','Active regional network','Genesee & Wyoming’s Georgia Southwestern Railroad interchanges with Heart of Georgia Railroad at Americus and connects elsewhere to Norfolk Southern. SAM Shortline is separate tourism/passenger context.','Rail proximity and network access do not establish parcel-level service, siding feasibility, freight demand, easements, capacity, or suitability for the Liberty project. Liberty rail use is not established.']
  ];
  const priorityCards=priorities.map(([category,title,detail,guardrail])=>`<article class="priority-card"><span>${escapeHtml(category)}</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(detail)}</p>${guardrail?`<small>${escapeHtml(guardrail)}</small>`:''}</article>`).join('');
  const financeSection=sectionMap.get('Public Financial Baseline');
  const financeItem=(title)=>financeSection?.items?.find((item)=>item.title===title);
  const financeDrawer=(title,item,ids,note='')=>evidenceControl(`View ${title} financial evidence`,ids,`<div class="drawer-copy">${item?`<p>${escapeHtml(item.detail)}</p>`:''}${note?`<p class="method-note">${escapeHtml(note)}</p>`:''}</div>`);
  const evidenceGroups=[
    ['Liberty development agreement',['liberty-agreement']],
    ['November 2025 E-SPLOST',['sumter-2025-ballot','sumter-2025-election-results']],
    ['City FY2024 audit',['city-americus-fy2024-acfr']],
    ['County audit',['sumter-county-fy2024-audit']],
    ['School audits',['sumter-schools-fy2024-audit','furlow-fy2025-audit']],
    ['Moratorium draft',['moratorium-draft','sumter-current-agendas']],
    ['Parcel maps',['liberty-agreement']],
    ['Campus rendering',['liberty-rendering']],
    ['Wetlands report and map',['terracon-map','terracon-wetlands']],
    ['Regional energy sources',['georgia-power-transmission','meag-its','sumter-emc','sertp']],
    ['Rail and regional connectivity',['gswr-official','hog-official','sam-shortline']],
    ['Education and workforce',['sgtc-gsw-partnership','gsw-server','ignite-cca','sumter-emc-youth']],
    ['Current community sources',['americus-downtown-streetscape','select-sumter-current','gsw-fuller-housing','phoebe-sumter-childcare']]
  ];
  const sections=[
    {id:'case-happening',nav:'What’s happening',html:`
      <section class="case-section case-opening" id="case-happening"><div class="case-heading"><p class="eyebrow">01 · Project and public context</p><h2>Liberty’s long-term project, in context</h2><p>A signed public agreement describes a phased technology campus. The strongest outcome is one where the project succeeds and Americus / Sumter is stronger because of it.</p></div>
      <div class="fact-ribbon"><div><strong>$1B–$5B</strong><span>Approximate investment commitment</span></div><div><strong>4 phases</strong><span>Phase 1 by 2029; later phases by 2033</span></div><div><strong>150+</strong><span>Full-time jobs at about $80K average wage</span></div><div><strong>At least 30 years</strong><span>Continuous-operation commitment</span></div></div>
      <div class="site-visual-sequence"><figure><img src="assets/americus/americus parcel.png" alt="Public parcel-map screenshot for the Americus project area"><figcaption><b>Parcel context.</b> Public map evidence; not title work or a surveyed boundary.</figcaption></figure><figure><img src="assets/americus/americus-tech-campus-rendering.jpg" alt="Preliminary draft rendering of the Americus technology campus"><figcaption><b>Preliminary concept.</b> Illustrates phasing; not final engineering or proof of fit.</figcaption></figure><figure><img src="assets/americus/wetland-delineation-map-2023.jpg" alt="Terracon wetland delineation map for the Swett Avenue study area"><figcaption><b>Wetland delineation.</b> A design and permitting input—not proof that development cannot proceed.</figcaption></figure></div>
      <div class="case-split"><div>${caseCard('Community & Governance Readiness','PROPOSED / DRAFT — ADOPTION NOT VERIFIED. The joint resolution would create an up-to-18-month pause while land use, electricity, agriculture, water, wastewater, noise, lighting, generators, adjacent-property impacts, and data-center standards are studied.','REPORTED')}</div><aside class="recommendation"><span>Community Forward recommendation</span><p>Use the governance-review period to align project development, public protections, clear information, and long-term community value.</p></aside></div>
      ${evidenceControl('View project, environmental, and governance evidence',['liberty-agreement','liberty-rendering','americus-parcel','terracon-map','terracon-wetlands','moratorium-draft'])}</section>`},
    {id:'case-building',nav:'Already building',html:`
      <section class="case-section" id="case-building"><div class="case-heading"><p class="eyebrow">02 · Existing momentum</p><h2>What Americus / Sumter is already building</h2><p>Americus is not waiting for outside investment to become a community worth investing in. Residents, institutions, and local government are already building toward the future.</p></div><div class="priority-grid">${priorityCards}</div><aside class="recommendation"><span>What could we build together?</span><p>Connect major private investment with documented public momentum. Strengthen what is underway before proposing something that duplicates it.</p></aside>${evidenceControl('View public-investment, rail, and community-priority evidence',['sumter-2025-ballot','sumter-2025-election-results','americus-downtown-streetscape','select-sumter-current','sgtc-gsw-partnership','phoebe-sumter-childcare','gefa-dwsrf-2025','gswr-official','hog-official','sam-shortline'])}</section>`},
    {id:'case-value',nav:'Community value',html:`
      <section class="case-section case-feature" id="case-value"><div class="case-heading"><p class="eyebrow">03 · Main community opportunity</p><h2>What could we build together?</h2><p>Collaboration could expand workforce, youth, energy, and infrastructure benefits beyond the project site.</p></div><div class="concept-callout"><span>Community Forward recommendation</span><h3>Former Americus High → Youth + Technology Hub</h3><p class="lead">Preserve a public asset. Give it a new youth-development mission: <strong>Create with technology, not simply consume it.</strong></p></div>
      <div class="asset-flow"><div><span>Existing public asset</span><strong>Former Americus High</strong><small>Ownership, condition, rehabilitation, and code compliance require confirmation.</small></div><span aria-hidden="true">→</span><div><span>Potential public mission</span><strong>Youth + Technology Hub</strong><small>Recreation, skating, esports, media, robotics, coding, AI, drones, electronics, cybersecurity, tutoring, and mentoring.</small></div></div>
      <div class="pathway-visual" aria-label="Youth development pathway"><span>Middle school<br><small>belonging + creation</small></span><b>→</b><span>High-school CTAE</span><b>→</b><span>SGTC + GSW</span><b>→</b><span>Credentials + apprenticeship</span><b>→</b><span>Local technical work</span></div>
      <div class="ownership-compare"><article><span>Project / corporate facility</span><h3>Liberty-campus Innovation Center</h3><p>May create project value but sits within a secured operating environment.</p></article><article><span>Community-owned public asset</span><h3>Public Youth + Technology Hub</h3><p>Publicly accessible, locally governed, and durable through developer or tenant changes.</p></article></div>
      <aside class="recommendation"><span>Feasibility gate</span><p>This concept is not approved. Confirm title, structural and environmental condition, rehabilitation cost, accessibility, code compliance, public ownership, transportation, staffing, safeguarding, and a long-term operating plan.</p></aside>${evidenceControl('View Americus High, youth, and pathway evidence',['former-americus-high-report','sumter-2025-ballot','ignite-cca','sgtc-gsw-partnership','gsw-server'])}</section>`},
    {id:'case-horizon',nav:'Long-term value',html:`
      <section class="case-section" id="case-horizon"><div class="case-heading"><p class="eyebrow">05 · Durability and operating ownership</p><h2>Building long-term community value</h2><p>Community investment should be designed for the same long horizon as the project—not as a collection of one-time gifts.</p></div>
      <div class="horizon-timeline"><div><b>2026</b><span>Agreement effective</span></div><div><b>2029</b><span>Phase 1 deadline</span></div><div><b>2033</b><span>Later-phase deadline</span></div><div class="verified-horizon"><b>At least 30 years</b><span>VERIFIED continuous-operation commitment</span></div><div class="unknown-horizon"><b>Community-benefit term</b><span>RESEARCH NEEDED — not verified in a controlling public source</span></div></div>
      <div class="legacy-grid"><article><h3>Upfront + phased capital</h3><p>Match contributions to construction milestones and verified community priorities.</p></article><article><h3>Recurring operations</h3><p>Support instructors, transport, maintenance, programming, and equipment refresh.</p></article><article><h3>Public ownership</h3><p>Keep community-facing assets accessible and accountable outside the secured campus.</p></article><article><h3>Successor protection</h3><p>Carry obligations through ownership changes and protect the community from early closure.</p></article></div>
      <p class="guardrail"><strong>Capital is only the beginning.</strong> Facilities and programs may require instructors, youth staff, transportation, utilities, security, insurance, maintenance, subscriptions, programming, and technology or battery replacement.</p>
      <aside class="recommendation"><span>Community Forward recommendation</span><p>Align community investment more closely with the long operating horizon of the project through enforceable, publicly reported, successor-protected commitments.</p></aside>${evidenceControl('View project-term and legacy evidence',['liberty-agreement','city-americus-fy2024-acfr','sumter-schools-fy2024-audit'])}</section>`},
    {id:'case-resilience',nav:'Jobs + energy',html:`
      <section class="case-section" id="case-resilience"><div class="case-heading"><p class="eyebrow">04 · Connected opportunity</p><h2>Jobs, Energy &amp; Community Resilience</h2><p>The agreement establishes direct commitments. Wider workforce and household benefits remain opportunities that require separate programs, ownership, and measurement.</p></div>
      <div class="jobs-ecosystem"><article class="job-commit"><span>Verified Liberty commitment</span><strong>150+</strong><p>Full-time jobs · approximately $80K average wage</p></article><article><span>Construction</span><strong>≈250</strong><p>Workers identified in the agreement; temporary work remains separate.</p></article><article><span>Broader ecosystem opportunity — count not established</span><strong>No established count</strong><p>NanoPV, electricians, solar/storage, HVAC, controls, networking, fiber, technicians, cybersecurity, suppliers, and future employers.</p></article></div>
      <p class="guardrail"><strong>Attribution rule:</strong> broader local jobs are not part of Liberty’s 150-job commitment unless documentation establishes that. Report occupation, employer, location, duration, and direct/contractor/vendor status.</p>
      <div class="energy-resilience-grid"><article><h3>Publicly established regional infrastructure</h3><div class="energy-flow"><span>Georgia Power</span><span>Sumter EMC</span><span>North Americus–Palmyra 230 kV corridor</span><span>MEAG / public-power context</span><span>Crisp / Ellaville regional context</span></div><p>Americus already sits within meaningful regional energy infrastructure. The next step is project-specific confirmation.</p></article><article><h3>Liberty-specific service details</h3><ul><li>Exact MW and phased load</li><li>Serving arrangement, will-serve terms, and source substation</li><li>Upgrades, timing, and cost allocation</li></ul><span class="badge status-research-needed">RESEARCH NEEDED</span></article><article class="resilience-options"><h3>Household resilience choices</h3><div><span>Home<br><small>efficiency · HVAC · wiring</small></span><span>Renter<br><small>inclusive benefit design</small></span><span>Community<br><small>solar · storage · emergency services</small></span><span>Resilience hub<br><small>backup · local jobs</small></span></div><p>Measure household energy-burden reduction and durable local employment—not panel count.</p></article></div>
      <aside class="recommendation"><span>Opportunity to strengthen the partnership</span><p>Turn one employment commitment into a broader workforce ecosystem—and use major digital infrastructure to strengthen household and community energy resilience.</p></aside>${evidenceControl('View jobs, energy, and resilience evidence',['liberty-agreement','georgia-power-transmission','meag-its','sumter-emc','sertp','nanopv','sgtc-gsw-partnership'])}</section>`},
    {id:'case-unknowns',nav:'Still to establish',html:`
      <section class="case-section" id="case-unknowns"><div class="case-heading"><p class="eyebrow">06 · Decision-grade diligence</p><h2>What still needs to be established</h2><p>These are the few high-value questions that still require controlling documents, engineering, institutional commitments, or public action.</p></div><div class="unknowns-grid"><span>Liberty-specific power and phased load</span><span>Water and wastewater engineering capacity</span><span>Final civil and wetland plan</span><span>Exact permanent job mix</span><span>Adopted ordinance or moratorium status</span><span>Education partnership terms</span><span>Community-benefit or endowment term</span><span>Former Americus High title and condition</span></div>
      <div class="financial-background"><div class="case-heading"><p class="eyebrow">Financial evidence · background</p><h3>Operating capacity matters after construction</h3><p>Capital projects create recurring staffing, maintenance, transportation, utility, and technology costs. Detailed audit evidence is available below without turning the case page into a financial model.</p></div>
      ${evidenceControl('View City financial evidence',['city-americus-fy2024-acfr','city-americus-fy2023-acfr'],`<div class="drawer-copy"><p>${escapeHtml(financeItem('City personnel-cost evidence')?.detail||'')}</p><p>${escapeHtml(financeItem('City General Fund FY2024')?.detail||'')}</p><p>${escapeHtml(financeItem('City Water and Sewer Fund FY2024')?.detail||'')}</p><p>${escapeHtml(financeItem('City audit-control risk')?.detail||'')}</p><p class="method-note">FY2024 is controlling. FY2023 is retained only as historical evidence.</p></div>`)}
      ${evidenceControl('View school financial evidence',['sumter-schools-fy2024-audit','furlow-fy2025-audit'],`<div class="drawer-copy"><p><strong>Sumter Schools FY2024:</strong> direct salary and complete benefit expense are not reported. TRS contribution-schedule covered payroll is $21,751,233; OPEB covered-employee payroll is $23,078,833; governmental fund balance is $24,475,466.</p><p><strong>Furlow FY2025:</strong> direct salary and complete benefit expense are not reported. TRS contribution-schedule covered payroll is $3,948,820; OPEB covered-employee payroll is $3,658,239; fund balance is $7,041,325.</p><p class="method-note">Covered payroll is corroborating evidence—not salary expense. Payable balances are liabilities, not annual personnel expense.</p></div>`)}
      ${evidenceControl('View public investment evidence',['sumter-2025-ballot','sumter-2025-election-results','sumter-budget-2025','gefa-dwsrf-2025'],`<div class="drawer-copy"><p><strong>VERIFIED November 2025 school E-SPLOST:</strong> one cent for up to 20 calendar quarters; maximum $45M collections; up to $50M general-obligation bonds; Athletic and Sports Complex and technology capital included; voter approval with 3,263 YES, 1,022 NO, 76.15% YES, and all 11 precincts reporting.</p><p class="method-note">The $50M bond authorization is not the same as the $45M projected E-SPLOST collections.</p><p>The community is already funding major school, transportation, and water capital. Authorization and budget availability do not prove that every project is designed, contracted, or complete.</p><p class="method-note">Any new facility or program also needs a sustainable operating plan.</p></div>`)}</div>
      <aside class="recommendation"><span>Professional confirmation</span><p>Utility, engineering, environmental, legal, financial, education, property, and governance professionals must resolve these issues before decision-grade conclusions are made.</p></aside></section>`},
    {id:'case-evidence',nav:'Evidence',html:`
      <section class="case-section evidence-library" id="case-evidence"><div class="case-heading"><p class="eyebrow">Public source library</p><h2>Evidence</h2><p>Open the grouped records behind the case. Classifications appear here once: VERIFIED, REPORTED, INFERENCE, and RESEARCH NEEDED.</p></div><div class="evidence-classification"><span class="badge status-verified">VERIFIED</span><p>Primary or authoritative evidence.</p><span class="badge status-reported">REPORTED</span><p>Public claims not independently established.</p><span class="badge status-inference">INFERENCE</span><p>Analysis based on cited evidence.</p><span class="badge status-research-needed">RESEARCH NEEDED</span><p>Not established in controlling public evidence.</p></div><div class="evidence-groups">${evidenceGroups.map(([label,ids])=>evidenceControl(label,ids)).join('')}</div><p class="case-disclaimer">This is public-information community integration analysis—not a site recommendation, engineering conclusion, legal opinion, or statement of community consent.</p></section>`}
  ];
  const order=['case-happening','case-building','case-value','case-resilience','case-horizon','case-unknowns','case-evidence'];
  sections.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
  els.americusProfile.hidden=false;
  els.americusNav.innerHTML=sections.map((section)=>`<a href="#${escapeHtml(section.id)}">${escapeHtml(section.nav)}</a>`).join('');
  els.americusStack.innerHTML=sections.map((section)=>section.html).join('');
}

function renderProfile(data,preliminary=false){const c=data.community;setText('community-name',c.name||c.resolved_name||state.query||'Public-data preview');setText('classification',c.classification||'Preliminary screening shell — no recommendation or score');setText('population',c.population);setText('geography',[c.county,c.municipality].filter(Boolean).join(' / ')||c.name);setText('utility',c.utility||c.utility_providers?.join(', '));setText('rail',c.rail||c.rail_operator);setText('signal',c.signal||c.major_infrastructure_signals?.join(', '));setText('confidence',c.confidence);els.badge.textContent=data.disclaimer||(preliminary?'Preliminary Public-Source Sample — Not a Recommendation':'Synthetic Demonstration');els.badge.className=`badge ${preliminary?'badge-live':'badge-synthetic'}`;}

function renderGeography(data){const g=data.geography_resolution||{search_geography:state.query||researchNeeded,municipalities:[],county:researchNeeded,zip_codes:[],utility_service_areas:[],school_districts:[],development_authorities:[],rail_corridors:[],tags:['Research Needed']};setText('search-geography',state.query||g.search_geography);const serviceParts=[...(g.utility_service_areas||[]),...(g.school_districts||[]),...(g.rail_corridors||[])];setText('service-geography',serviceParts.join(' · ')||researchNeeded);const chain=[['Input',state.query||g.search_geography],['Municipality',(g.municipalities||[]).join(', ')],['County',g.county],['Related ZIPs',(g.zip_codes||[]).join(', ')],['Utility service',(g.utility_service_areas||[]).join(', ')],['School system',(g.school_districts||[]).join(', ')],['Development / rail / region',[...(g.development_authorities||[]),...(g.rail_corridors||[])].join(', ')]];els.geographyChain.innerHTML=chain.map(([label,value])=>`<article><span>${escapeHtml(label)}</span><strong>${escapeHtml(value||researchNeeded)}</strong></article>`).join('<span class="chain-arrow" aria-hidden="true">→</span>');els.relationshipTags.innerHTML=(g.tags||[]).map((tag)=>`<span>${escapeHtml(tag)}</span>`).join('');document.querySelectorAll('.service-project').forEach((node)=>node.remove());const projectHtml=(data.infrastructure_projects||[]).map((project)=>`<article class="service-project"><div>${badge(project.evidence_status)}<h3>${escapeHtml(project.name)}</h3></div><dl><dt>Project Location</dt><dd>${escapeHtml(project.project_location_zip||researchNeeded)}</dd><dt>Serving Utility</dt><dd>${escapeHtml(project.serving_utility||researchNeeded)}</dd><dt>Utility Service Territory</dt><dd>${escapeHtml((project.utility_service_territory||[]).join(', ')||researchNeeded)}</dd><dt>Potential Service-Area Impact</dt><dd>${escapeHtml(project.potential_service_area_impact||researchNeeded)}</dd><dt>Confirmed Capacity Impact</dt><dd>${project.confirmed_capacity_impact==null?'Unknown — no capacity claim':escapeHtml(project.confirmed_capacity_impact)}</dd><dt>Requires Utility Verification</dt><dd>${project.requires_utility_verification?'Yes':'No'}</dd></dl></article>`).join('');els.relationshipTags.insertAdjacentHTML('afterend',projectHtml);els.researchControl.textContent=data.research_status||'NEW_RESEARCH_REQUIRED';els.researchControl.className=`badge ${statusClass(data.research_status||'NEW_RESEARCH_REQUIRED')}`;els.researchControl.dataset.fetchCount=String([...state.researchRuns.values()].reduce((sum,count)=>sum+count,0));els.researchControl.dataset.cacheEntries=String(state.dataCache.size);}

const narrativeMeta=[['needs','What the Community Needs','01'],['funding','What Residents Are Funding','02'],['exists','What’s Here Today','03'],['coming','What’s On the Way','04'],['underused','What Could Be Reused','05'],['matches','Where Investment Could Help','06'],['legacy','What Could Last for a Generation','07']];
function renderNarrative(data){const narrative=data.narrative||{};els.narrative.innerHTML=narrativeMeta.map(([key,title,number])=>{const items=narrative[key]||[{title:researchNeeded,detail:'Approved public-source research is required.',status:researchNeeded}];return `<article class="narrative-row"><div class="narrative-title"><span>${number}</span><h3>${escapeHtml(title)}</h3></div><div class="narrative-items">${items.map((item)=>`<div><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.detail)}</p>${badge(item.status)}</div>`).join('')}</div></article>`;}).join('');}
function emptyLayer(text){return `<div class="layer-item"><p>${escapeHtml(text)}</p>${badge(researchNeeded)}</div>`;}
function renderSystemLayers(data){const fiscal=data.fiscal_measures||[];els.fiscal.innerHTML=fiscal.length?fiscal.map((item)=>`<div class="layer-item"><div><strong>${escapeHtml(item.type)}</strong><small>${escapeHtml(item.role)}</small></div><p>${escapeHtml(item.detail||'Research has not been run.')}</p>${badge(item.status)}</div>`).join(''):emptyLayer('SPLOST, E-SPLOST and LOST must be researched separately.');const enterprise=data.enterprise_funds||[];els.enterprise.innerHTML=enterprise.length?enterprise.map((item)=>`<div class="layer-item"><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.accounting_boundary)}</small></div><p>${escapeHtml(item.ratepayer_benefit||'Requires utility financial analysis. Never promises lower rates.')}</p>${badge(item.status)}</div>`).join(''):emptyLayer('Enterprise funds remain separate from ordinary General Fund revenue.');const matches=data.capital_matches||[];els.capitalMatches.innerHTML=matches.length?matches.map((item)=>`<div class="capital-item"><strong>${escapeHtml(item.community_need)}</strong><dl><dt>Existing local funding</dt><dd>${escapeHtml(item.existing_local_funding)}</dd><dt>Potential match</dt><dd>${escapeHtml(item.potential_match)}</dd><dt>Private participation</dt><dd>${escapeHtml(item.potential_private_participation)}</dd><dt>Total leverage</dt><dd>${escapeHtml(item.total_leverage)}</dd></dl>${badge(item.status)}</div>`).join(''):emptyLayer('Eligibility and leverage require program-specific verification.');const future=data.future_research||[];els.futureResearch.innerHTML=future.length?future.map((item)=>`<div class="layer-item"><div><strong>${escapeHtml(item.title)}</strong></div><p>${escapeHtml(item.detail)}</p>${badge(item.status)}</div>`).join(''):emptyLayer('Geology, coastal water, housing, family attraction and future technology adaptability require additional research.');}

function normalizeScores(scores){if(Array.isArray(scores))return scores;return [['technical_opportunity','Technical Opportunity'],['data_center_market_maturity','Data Center Market Maturity'],['government_readiness','Government Readiness'],['community_need','Community Need'],['partnership_opportunity','Partnership Opportunity'],['existing_asset_leverage','Existing Asset Leverage'],['rail_corridor_leverage','Rail & Corridor Leverage'],['middle_school_engagement_technology_creation_readiness','Middle School Engagement & Technology Creation Readiness'],['community_risk','Community Risk']].map(([id,label])=>({id,label,value:scores?.[id]??null,direction:'Awaiting reviewed evidence',explanation:'The public preview does not force a numeric score when evidence is incomplete.'}));}
function renderScores(scores,preliminary=false){const normalized=normalizeScores(scores);els.scoreGrid.innerHTML=normalized.map((score)=>{const empty=score.value==null;return `<button class="score-card ${score.id==='risk'||score.id==='community_risk'?'risk':''}" type="button" data-score="${escapeHtml(score.id)}"><span class="score-arrow" aria-hidden="true">↗</span><h3>${escapeHtml(score.label)}</h3><div class="score-value ${empty?'is-empty':''}">${empty?'Insufficient Evidence':`${score.value}<small>/100</small>`}</div><div class="score-track" aria-hidden="true"><span style="width:${empty?0:score.value}%"></span></div><p>${escapeHtml(score.direction)}</p></button>`;}).join('');els.scoreGrid.querySelectorAll('.score-card').forEach((button)=>button.addEventListener('click',()=>openScore(normalized.find((score)=>score.id===button.dataset.score),preliminary)));}
function openScore(score,preliminary){els.dialogTitle.textContent=score.label;const value=score.value==null?'Insufficient Evidence':`${score.value}/100`;els.dialogBody.innerHTML=`<div class="dialog-score ${score.value==null?'is-empty':''}">${escapeHtml(value)}</div><p><strong>Direction:</strong> ${escapeHtml(score.direction)}</p><p>${escapeHtml(score.explanation)}</p><p><strong>Control:</strong> ${preliminary?'No real-community score is generated from geography resolution alone.':'This score remains separate and does not override other dimensions or professional review.'}</p>`;els.dialog.showModal();}

function researchShellSections(){return ['Future Power Infrastructure','Industrial Reuse','Rail & Corridor Opportunity','Water & Wastewater','Public Capital','Agriculture','Middle School Engagement & Technology Creation','Workforce & Education','Housing & Tax-Base Renewal','Geology & Subsurface','Governance & Community Risk'].map((title,index)=>({id:`research-${index}`,title,icon:['⚡','🏭','🚆','💧','🏛️','🌾','🛠️','🎓','🏘️','🪨','⚖️'][index],filter:'verification',summary:'Public-source retrieval and evidence validation are required.',facts:[{label:'Status',value:researchNeeded,status:researchNeeded}],proves:'Nothing is established by geography resolution alone.',unknown:'Source discovery, dates, conflicts, geographic fit and current conditions.',confirmation:'Appropriate professional and local review.'}));}
function renderResearch(sections){if(!sections?.length)sections=researchShellSections();els.nav.innerHTML=sections.map((section)=>`<a href="#${escapeHtml(section.id)}"><span aria-hidden="true">${section.icon}</span>${escapeHtml(section.title)}</a>`).join('');els.researchGrid.innerHTML=sections.map((section)=>`<article class="research-card ${section.prominent?'is-prominent':''}" id="${escapeHtml(section.id)}" data-filter="${escapeHtml(section.filter)}"><button class="card-button" type="button" aria-expanded="false"><span class="card-icon" aria-hidden="true">${section.icon}</span><span><strong>${escapeHtml(section.title)}</strong><small>${escapeHtml(section.summary)}</small></span><span class="chevron" aria-hidden="true">＋</span></button><div class="card-body"><div class="facts">${section.facts.map((fact)=>`<div class="fact"><span class="fact-label">${escapeHtml(fact.label)}</span><span class="fact-value">${escapeHtml(fact.value)}${fact.state==='planned'?'<span class="planned-marker">Planned</span>':''}</span>${badge(fact.status)}</div>`).join('')}</div><details class="evidence-details"><summary>Evidence, limits & confirmation</summary><div class="evidence-panel"><p><strong>What it proves:</strong> ${escapeHtml(section.proves)}</p><p><strong>Unknowns:</strong> ${escapeHtml(section.unknown)}</p><p><strong>Required confirmation:</strong> ${escapeHtml(section.confirmation)}</p></div></details></div></article>`).join('');els.researchGrid.querySelectorAll('.card-button').forEach((button)=>button.addEventListener('click',()=>{const card=button.closest('.research-card');const open=card.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));}));applyFilter(state.filter);}
function renderPathway(pathway){if(!pathway?.length)pathway=['Elementary exposure','Middle-school creation','High-school CTAE','9th-grade bridge','Dual enrollment','College + credentials','Paid work-based learning','Local technology work'].map((stage)=>({stage,status:'research',note:researchNeeded}));els.pathway.innerHTML=pathway.map((item)=>`<article class="pathway-stage ${escapeHtml(item.status)}"><strong>${escapeHtml(item.stage)}</strong><span>${escapeHtml(item.status)}</span><p>${escapeHtml(item.note)}</p></article>`).join('');}
function renderOpportunities(items){if(!items?.length)items=[{title:'Opportunity relationships require evidence',condition:researchNeeded,signal:researchNeeded,response:'No opportunity is generated until a documented community condition and infrastructure signal are linked.',status:'Insufficient Evidence',confirmation:'Public sources, evidence validation and human review'}];els.opportunities.innerHTML=items.map((item)=>`<article class="opportunity-card">${badge(item.status)}<h3>${escapeHtml(item.title)}</h3><div class="opportunity-flow"><span><strong>Condition</strong><br>${escapeHtml(item.condition)}</span><span class="opportunity-arrow" aria-hidden="true">→</span><span><strong>Signal</strong><br>${escapeHtml(item.signal)}</span></div><dl><dt>Potential response</dt><dd>${escapeHtml(item.response)}</dd><dt>Confirmation</dt><dd>${escapeHtml(item.confirmation)}</dd></dl></article>`).join('');}
function renderSources(sources){els.sources.innerHTML=(sources?.length?sources:[{title:'Approved source registry',type:researchNeeded,date:'Human review required'}]).map((source)=>`<div class="source-item"><strong>${escapeHtml(source.title)}</strong><span>${escapeHtml(source.type)} · ${escapeHtml(source.date)}</span></div>`).join('');}
function renderLegacy(data,horizon=state.horizon){state.horizon=Number(horizon);const items=data.narrative?.legacy||[{title:researchNeeded,detail:'Potential outcomes require evidence.',status:'Insufficient Evidence'}];const limit=state.horizon===10?2:state.horizon===20?3:items.length;els.legacy.innerHTML=items.slice(0,limit).map((item,index)=>`<article><span>${index+1}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.detail)}</p>${badge(item.status)}</article>`).join('');document.querySelectorAll('[data-horizon]').forEach((button)=>button.classList.toggle('is-active',Number(button.dataset.horizon)===state.horizon));}
function renderAll(data,preliminary=false){state.data=data;renderProfile(data,preliminary);renderGeography(data);renderNarrative(data);renderSystemLayers(data);renderScores(data.scores,preliminary);renderResearch(data.sections);renderPathway(data.pathway);renderOpportunities(data.opportunities);renderLegacy(data);renderSources(data.sources);document.querySelector('#hub').hidden=preliminary;}
function applyFilter(filter){state.filter=filter;document.querySelectorAll('.filter-button').forEach((button)=>{const active=button.dataset.filter===filter;button.classList.toggle('is-active',active);button.setAttribute('aria-pressed',String(active));});document.querySelectorAll('.research-card').forEach((card)=>{card.hidden=filter!=='all'&&card.dataset.filter!==filter;});}

async function showSynthetic({scroll=false}={}){setPublicRoute('',false);state.mode='synthetic';state.query='';const data=await loadJsonCached('data/pinehaven.json');els.input.value='';els.input.removeAttribute('aria-invalid');els.liveNotice.hidden=true;setViewMode(false);els.help.textContent='ZIP codes are starting points only. Community Forward Georgia expands the search to relevant municipalities, counties, school systems, utility service areas, and regional infrastructure.';updateModeButtons();renderAll(data,false);if(scroll)document.querySelector('#profile').scrollIntoView({behavior:'smooth'});}
function showQuickLanding(){setPublicRoute('',false);state.mode='live';state.query='';state.data=null;els.input.value='';els.input.removeAttribute('aria-invalid');els.liveNotice.hidden=true;setViewMode(true);els.quickView.hidden=true;els.americusProfile.hidden=true;els.help.textContent='ZIP codes are starting points only. Community Forward Georgia expands the search to relevant municipalities, counties, schools, utilities, development authorities, and regional institutions.';updateModeButtons();}
async function showLivePreview(query=''){
  const clean=query.trim();if(!clean){showQuickLanding();els.input.focus();els.help.textContent='Enter a Georgia ZIP code, city, or county to begin a Quick Community View.';return;}
  const resolved=await resolveGeorgiaQuickView(clean);
  if(resolved.error){els.input.setAttribute('aria-invalid','true');els.help.textContent=resolved.error;showToast(resolved.error);return;}
  const isAmericus=resolved.data.profile_id==='americus-sumter-quick-view';setPublicRoute(clean,isAmericus);state.mode='live';state.query=clean;state.data=resolved.data;els.input.value=clean;els.input.removeAttribute('aria-invalid');els.liveNotice.hidden=false;setViewMode(true);updateModeButtons();renderProfile(resolved.data,true);renderGeography(resolved.data);renderQuickView(resolved.data);if(isAmericus){state.americusProfile=await loadJsonCached('data/americus-sumter-profile.json?v=20260913.6');resolved.data.community_conditions=state.americusProfile.community_conditions;renderAmericusProfile(state.americusProfile);els.quickView.hidden=true;els.liveNotice.hidden=true;}else{els.americusProfile.hidden=true;}els.help.textContent=isAmericus?`Resolved ${clean} to the featured Americus / Sumter deep case.`:resolved.data.smoke_test_only?'Demo Quick View loaded with preloaded demonstration evidence. No live internet research was performed.':'Researching… Demo. The community is resolved; live research services are not connected in this public preview.';showToast(isAmericus?'Deep Community Analysis loaded.':resolved.data.smoke_test_only?'Demo Quick View loaded.':'Research workflow demo loaded.');document.querySelector(isAmericus?'#americus-deep-profile':'#quick-view').scrollIntoView({behavior:'smooth'});
}
function updateModeButtons(){els.modeButtons.forEach((button)=>{const active=button.dataset.mode===state.mode;button.classList.toggle('is-active',active);button.setAttribute('aria-pressed',String(active));});}
function showToast(message){els.toast.textContent=message;els.toast.classList.add('is-visible');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.classList.remove('is-visible'),3600);}

els.modeButtons.forEach((button)=>button.addEventListener('click',()=>button.dataset.mode==='synthetic'?showSynthetic():showLivePreview(els.input.value)));
els.americus.addEventListener('click',()=>showLivePreview('31709'));
els.featuredAmericus?.addEventListener('click',()=>showLivePreview('31709'));
els.pinehaven?.addEventListener('click',()=>showSynthetic({scroll:true}));
els.reset.addEventListener('click',()=>{applyFilter('all');state.horizon=30;showQuickLanding();window.scrollTo({top:0,behavior:'smooth'});showToast('Ready for a new Georgia community search.');});
els.search.addEventListener('submit',(event)=>{event.preventDefault();const query=els.input.value.trim();if(/pinehaven|31794/i.test(query))showSynthetic({scroll:true});else showLivePreview(query);});
document.querySelectorAll('.filter-button').forEach((button)=>button.addEventListener('click',()=>applyFilter(button.dataset.filter)));
document.querySelectorAll('[data-horizon]').forEach((button)=>button.addEventListener('click',()=>renderLegacy(state.data,button.dataset.horizon)));
els.close.addEventListener('click',()=>els.dialog.close());els.dialog.addEventListener('click',(event)=>{if(event.target===els.dialog)els.dialog.close();});
window.communityDemo={getDebugState:()=>({mode:state.mode,query:state.query,researchStatus:state.data?.research_status,fetchCounts:Object.fromEntries(state.researchRuns),cacheKeys:[...state.dataCache.keys()],entityCacheKeys:[...state.entityCache.keys()],zipCoverage:state.zipIndex?.count||null,ballotpediaDiscovery:state.data?.referendum_discovery||null,infrastructureProjects:state.data?.infrastructure_projects||[],fiscalMeasures:state.data?.fiscal_measures||[],enterpriseFunds:state.data?.enterprise_funds||[],deepProfile:state.americusProfile?.profile_id||null})};
const initialLocation=new URLSearchParams(window.location.search).get('location');
if(initialLocation)showLivePreview(initialLocation);else showQuickLanding();
